# Form implementation generated from reading ui file 'Project1gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 121, 16))
        self.label_2.setObjectName("label_2")
        self.Test1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Test1.setGeometry(QtCore.QRect(50, 140, 101, 16))
        self.Test1.setText("")
        self.Test1.setObjectName("Test1")
        self.Test2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Test2.setGeometry(QtCore.QRect(50, 180, 81, 16))
        self.Test2.setText("")
        self.Test2.setObjectName("Test2")
        self.Test3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Test3.setGeometry(QtCore.QRect(50, 220, 81, 16))
        self.Test3.setText("")
        self.Test3.setObjectName("Test3")
        self.Test4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Test4.setGeometry(QtCore.QRect(50, 260, 81, 16))
        self.Test4.setText("")
        self.Test4.setObjectName("Test4")
        self.Submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit_button.setGeometry(QtCore.QRect(240, 300, 56, 17))
        self.Submit_button.setObjectName("Submit_button")
        self.Name_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name_input.setGeometry(QtCore.QRect(210, 50, 113, 20))
        self.Name_input.setObjectName("Name_input")
        self.Num_attempts_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Num_attempts_input.setGeometry(QtCore.QRect(210, 90, 113, 20))
        self.Num_attempts_input.setObjectName("Num_attempts_input")
        self.Test1_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Test1_input.setGeometry(QtCore.QRect(210, 130, 113, 20))
        self.Test1_input.setObjectName("Test1_input")
        self.Test2_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Test2_input.setGeometry(QtCore.QRect(210, 170, 113, 20))
        self.Test2_input.setObjectName("Test2_input")
        self.Test3_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Test3_input.setGeometry(QtCore.QRect(210, 210, 113, 20))
        self.Test3_input.setObjectName("Test3_input")
        self.Test4_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Test4_input.setGeometry(QtCore.QRect(210, 260, 113, 20))
        self.Test4_input.setObjectName("Test4_input")
        self.Attempts_error = QtWidgets.QLabel(parent=self.centralwidget)
        self.Attempts_error.setGeometry(QtCore.QRect(330, 90, 171, 20))
        self.Attempts_error.setStyleSheet("color: rgb(255, 0, 0);")
        self.Attempts_error.setText("")
        self.Attempts_error.setObjectName("Attempts_error")
        self.Name_error = QtWidgets.QLabel(parent=self.centralwidget)
        self.Name_error.setGeometry(QtCore.QRect(350, 50, 141, 20))
        self.Name_error.setStyleSheet("color: rgb(255, 0, 0);")
        self.Name_error.setText("")
        self.Name_error.setObjectName("Name_error")
        self.Submit_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.Submit_message.setGeometry(QtCore.QRect(110, 320, 331, 20))
        self.Submit_message.setStyleSheet("color: rgb(255, 0, 0);")
        self.Submit_message.setText("")
        self.Submit_message.setObjectName("Submit_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student Name:"))
        self.label_2.setText(_translate("MainWindow", "Number of Attempts:"))
        self.Submit_button.setText(_translate("MainWindow", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
