# Form implementation generated from reading ui file 'Project1gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 400)
        MainWindow.setMinimumSize(QtCore.QSize(350, 400))
        MainWindow.setMaximumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 121, 16))
        self.label_2.setObjectName("label_2")
        self.Score1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score1.setGeometry(QtCore.QRect(50, 140, 101, 16))
        self.Score1.setObjectName("Score1")
        self.Score2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score2.setGeometry(QtCore.QRect(50, 180, 81, 16))
        self.Score2.setObjectName("Score2")
        self.Score3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score3.setGeometry(QtCore.QRect(50, 220, 81, 16))
        self.Score3.setObjectName("Score3")
        self.Score4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score4.setGeometry(QtCore.QRect(50, 260, 81, 16))
        self.Score4.setObjectName("Score4")
        self.Submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit_button.setGeometry(QtCore.QRect(150, 300, 56, 17))
        self.Submit_button.setObjectName("Submit_button")
        self.Name_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name_input.setGeometry(QtCore.QRect(210, 50, 113, 20))
        self.Name_input.setObjectName("Name_input")
        self.Num_attempts_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Num_attempts_input.setGeometry(QtCore.QRect(210, 90, 113, 20))
        self.Num_attempts_input.setObjectName("Num_attempts_input")
        self.Score1_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score1_input.setGeometry(QtCore.QRect(210, 130, 113, 20))
        self.Score1_input.setObjectName("Score1_input")
        self.Score2_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score2_input.setGeometry(QtCore.QRect(210, 170, 113, 20))
        self.Score2_input.setObjectName("Score2_input")
        self.Score3_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score3_input.setGeometry(QtCore.QRect(210, 210, 113, 20))
        self.Score3_input.setObjectName("Score3_input")
        self.Score4_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score4_input.setGeometry(QtCore.QRect(210, 260, 113, 20))
        self.Score4_input.setObjectName("Score4_input")
        self.Error_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error_message.setGeometry(QtCore.QRect(30, 330, 311, 20))
        self.Error_message.setObjectName("Error_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student Name:"))
        self.label_2.setText(_translate("MainWindow", "Number of Attempts:"))
        self.Score1.setText(_translate("MainWindow", "Score 1:"))
        self.Score2.setText(_translate("MainWindow", "Score 2:"))
        self.Score3.setText(_translate("MainWindow", "Score 3:"))
        self.Score4.setText(_translate("MainWindow", "Score 4: "))
        self.Submit_button.setText(_translate("MainWindow", "SUBMIT"))
        self.Error_message.setText(_translate("MainWindow", " ERROR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
